[build]
  command = "hugo"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.19"
  
# COMMENT: redirect rules with all the fields expanded
# According to netlify domain management
# https://app.netlify.com/sites/libjohn/settings/domain#domains
# # Redirect default Netlify subdomain to primary domain
# https://libjohn.netlify.com/* https://www.johnlittle.info/:splat 301!
[[redirects]]
  from = "https://rfun.netlify.com/*"
  to = "https://rfun.library.duke.edu/:splat"
  status = 301
  force = true
  
# redirect from when rmarkdown was 
# servied via blogdown::rfun inside the /static subdir
# i.e. symlink from /docs to 
# https://github.com/data-and-visualization/blogdown2-rfun/tree/master/static/rmarkdown
# then push blogdown2-rfun when netlify would rebuild site
# and store rmarkdown out of https://rfun.library.duke.edu/rmarkdown/
# New location will be served by connecting the docs 
# directory of this repo diretly netlify.  CNAME from the 
# folks in ITS will allow rmarkdown-rfun.netlify.com to 
# get served via rmarkdown.library.duke.edu
[[redirects]]
  from = "/rmarkdown/*"
  to = "https://rmarkdown.library.duke.edu/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/map/*"
  to = "https://map-rfun.library.duke.edu/:splat"
  status = 301
  force = true
 
[[redirects]] 
  from = "/intro2r/*"
  to = "https://intro2r.library.duke.edu/:splat"
  status = 301
  force = true

[[redirects]] 
  from = "/git/*"
  to = "https://git-rfun.library.duke.edu/:splat"
  status = 301
  force = true
  
[[redirects]] 
  from = "/ggplot/*"
  to = "https://ggplot.library.duke.edu/:splat"
  status = 301
  force = true


