# COMMENT: redirect rules with all the fields expanded
# According to netlify domain management
# https://app.netlify.com/sites/libjohn/settings/domain#domains
# # Redirect default Netlify subdomain to primary domain
# https://libjohn.netlify.com/* https://www.johnlittle.info/:splat 301!
[[redirects]]
  from = "https://rfun.netlify.com/*"
  to = "https://rfun.library.duke.edu/:splat"
  status = 301
  force = true
  
  
