[build]
command = 'hugo'
publish = 'public'
[build.environment]
HUGO_VERSION = '0.96.0'


[context]
[context.branch-deploy]
command = 'hugo -F -b $DEPLOY_PRIME_URL'

[context.deploy-preview]
command = 'hugo -F -b $DEPLOY_PRIME_URL'

[context.production]
[context.production.environment]
HUGO_ENV = 'production'

# COMMENT: redirect rules with all the fields expanded
# According to netlify domain management
# https://app.netlify.com/sites/libjohn/settings/domain#domains
# # Redirect default Netlify subdomain to primary domain
# https://libjohn.netlify.com/* https://www.johnlittle.info/:splat 301!
[[redirects]]
  from = "https://rfun.netlify.com/*"
  to = "https://rfun.library.duke.edu/:splat"
  status = 301
  force = true
  
# redirect from when rmarkdown was 
# servied via blogdown::rfun inside the /static subdir
# i.e. symlink from /docs to 
# https://github.com/data-and-visualization/blogdown2-rfun/tree/master/static/rmarkdown
# then push blogdown2-rfun when netlify would rebuild site
# and store rmarkdown out of https://rfun.library.duke.edu/rmarkdown/
# New location will be served by connecting the docs 
# directory of this repo diretly netlify.  CNAME from the 
# folks in ITS will allow rmarkdown-rfun.netlify.com to 
# get served via rmarkdown.library.duke.edu
[[redirects]]
  from = "portfolio/dashboard_workshop/*"
  to = "https://github.com/libjohn/workshop_textmining"
  status = 301
  force = true

[[redirects]]
  from = "portfolio/dashboard_workshop/*"
  to = "https://intro2r.library.duke.edu/"
  status = 301
  force = true

[[redirects]]
  from = "portfolio/slides_workshop/*"
  to = "https://intro2r.library.duke.edu/"
  status = 301
  force = true

[[redirects]]
  from = "portfolio/twitter/*"
  to = "https://intro2r.library.duke.edu/"
  status = 301
  force = true

[[redirects]]
  from = "portfolio/sql_and_databases/*"
  to = "https://github.com/libjohn/casestudy_bigquery_dbplyr"
  status = 301
  force = true

[[redirects]]
  from = "portfolio/scraping_workshop/*"
  to = "https://github.com/libjohn/workshop_webscraping"
  status = 301
  force = true

[[redirects]]
  from = "portfolio/case_study/*"
  to = "https://www.youtube.com/playlist?list=PLIUcX1JrVUNV_ihIoJX96I_c32Gp8_3h2"
  status = 301
  force = true

[[redirects]]
  from = "portfolio/rmarkdown_workshop/*"
  to = "https://intro2r.library.duke.edu/"
  status = 301
  force = true

[[redirects]]
  from = "portfolio/git_workshop/*"
  to = "https://git-rfun.library.duke.edu/"
  status = 301
  force = true

[[redirects]]
  from = "/portfolio/intro2r_workshop/*"
  to = "https://intro2r.library.duke.edu/"
  status = 301
  force = true

[[redirects]]
  from = "/portfolio/r_open_labs/*"
  to = "https://intro2r.library.duke.edu/"
  status = 301
  force = true

[[redirects]]
  from = "portfolio/shiny_workshop/*"
  to = "https://shiny.posit.co/r/getstarted/shiny-basics/lesson1/index.html"
  status = 301
  force = true

[[redirects]]
  from = "blog/data-sources-for-regression-analysis/*"
  to = "https://intro2r.library.duke.edu/data-sources-for-regression-analysis"
  status = 301
  force = true

[[redirects]]
  from = "/rmarkdown/*"
  to = "https://rmarkdown.library.duke.edu/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/map/*"
  to = "https://map-rfun.library.duke.edu/:splat"
  status = 301
  force = true
 
[[redirects]] 
  from = "/intro2r/*"
  to = "https://intro2r.library.duke.edu/:splat"
  status = 301
  force = true

[[redirects]] 
  from = "/git/*"
  to = "https://git-rfun.library.duke.edu/:splat"
  status = 301
  force = true
  
[[redirects]] 
  from = "/ggplot/*"
  to = "https://ggplot.library.duke.edu/:splat"
  status = 301
  force = true


