---
title: 'Reproducibility: Version Control, Git, and RStudio'
author: John Little
date: '2018-08-09'
description: 'Resources for git workshop'
slug: reproducibility-version-control-git-and-rstudio
categories:
  - Workshops
  - Git
  - Reproducibility
  - Data-Management
  - Version-Control
tags: []
featured: ''
featuredalt: ''
featuredpath: ''
linktitle: ''
---

Sophia Lafferty-Hess ([DVS Staff page](https://library.duke.edu/data/about/staff)), Jen Darragh ([DVS Staff page](https://library.duke.edu/data/about/staff)), and [I](https://johnlittle.info/) presented a **Reproducibility** workshop hosted by the [Data and Visualization Services Department](https://library.duke.edu/data/) and cross-listed with the Responsible Conduct of Research (RCR) training efforts. 

The workshops, officially entitled *Reproducibility: RStudio and Git* is a hands-on response to the importance of reproducibility, replication, and transparency in the research endeavor. General data management strategies are introduced to assist researchers in their efforts towards increased research reproducibility. 

The hands-on exercises focuses on how **Git** and **RStudio** can work seamlessly together in support of reproducible research. 

No previous experience with Git or R is required.  However minimal experience with R is a plus due to the interoperable utility of the two specific tools (git and RStudio).  Combining the two tools, which build on R's widely extensible ecosystem, yields a powerful, reproducible-friendly and collaborative-friendly platform.  For those who are not familiar with R, RStudio or Git, you may want to view the streaming video link from a previous post: [Introduction to R](/2017/09/18/reproducibility-data-management-git-and-rstudio-workshop-fall-2017/).

**Learning resources** and **workshop materials** are available and shareable.  The software (R, RStudio, Git) is open-source and free.  Use the links below to learn at your own pace and at the comfort of your own workspace.  

- [Streaming Video](https://library.capture.duke.edu/Panopto/Pages/Viewer.aspx?id=36b63692-7297-4f97-b1be-19cd57511d95)
- [Online Guide](http://rfun.library.duke.edu/git/)
- [Reproducibility Slides](https://osf.io/kdr2w/)
- [Git & RStudio Slides](http://rfun.library.duke.edu/git/slides/#1)
- [DVS Description / Resources](http://library.duke.edu/data/news/past-workshops#git)