---
title: Rfun Schedule - Spring 2017
author: john little
date: '2017-01-16'
slug: rfun-schedule-spring-2017
categories:
  - calendar
tags:
  - schedule
---

## Meeting Schedule

**When**: Thursday's at noon, Spring 2017

**Who**: R enthusiasts, beginngers through advanced 

**Where**: Workshop Room, The /Edge, Bostock Library

```{r setup, include=FALSE}

library(tidyverse)

rfun_table <- read_csv('https://github.com/data-and-visualization/blogdown2-rfun/raw/master/static/data/data.csv')
```


```{r, echo=FALSE}
rfun_table %>% 
  select(Date, Topic, Presenter, Video = VideoURL, Files = FilesURL) %>% 
  knitr::kable()
```


```{r}
rfun_table %>% 
  mutate(present2 = paste0("<a href='", PresenterURL, "'>", Presenter, "</a>")) %>%
  mutate(topic2 = paste0("<a href='", TopicURL, "'>", Topic, "</a>")) %>% 
  mutate(vid2 = paste0("<a href='", VideoURL, "'>", Video, "</a>")) %>% 
  mutate(file2 = paste0("<a href='", FilesURL, "'>", Files, "</a>")) %>% 
  select(Topic = topic2, Presenter = present2, Video = vid2, Files = file2) %>% 
  knitr::kable()


rfun_table %>% 
  mutate(present2 = paste0("<a href='", PresenterURL, "'>", Presenter, "</a>")) %>%
  mutate(topic2 = paste0("<a href='", TopicURL, "'>", Topic, "</a>")) %>% 
  mutate(vid2 = if_else(Video == "NA", " ", paste0("<a href='", VideoURL, "'>", Video, "</a>", "foo"))) %>% 
  mutate(file2 = paste0("<a href='", FilesURL, "'>", Files, "</a>")) %>% 
  select(Video, Topic = topic2, Presenter = present2, vid2, Files = file2) %>% 
  knitr::kable()




```

