---
title: New RFUN URL
author: John Little
date: '2017-08-28'
slug: new-url
categories: 
  - Announcement
  - "Resource Links"
---

## http://rfun.library.duke.edu

DVS is pleased to announce the new official URL of the RFUN series:  http://rfun.library.duke.edu.  With this seemingly minor change we accomplish several practical goals.  

### Using R and R Studio to manage the RFUN web presence

This web site is composed in R Markdown via RStudio using the `blogdown` package.  The site repository is on [github](https://github.com/data-and-visualization/Rfun) and hosted at netlify.com.  You can [read more](https://bookdown.org/yihui/blogdown/) about this process.

### Eating our own Dogfood

Here in the [Data & Visualization Services Department](http://library.duke.edu/data/) we promote R as an excellent and practical data science platform/tool/language.  We host the RFun series as a way of helping people learn more about R.  This site is one real-world example of how using good Data Management principles (version control + reproducibility) can be implemented to produce practical reports -- reports in this case are a website generated from R scripts.  This site tends to host announcements and links to resources more so than present research analysis, but analysis and reporting can be integrated into the same tool:  R.

### Hosting Resources

Because of the hosting and scripting capabilities we've decided to host some of our resources right here at [RFun](http://rfun.library.duke.edu/).  Since the resources are created in R, and designed to highlight R capabilities, we decided to show you how your learning resources can also be developed in R.  Currently the next two resources are in draft mode.  We're sharing them now as previews of the learning resource materials.  If you find a bug or error, rest assured it will be [ready by the date of workshops](/2017/08/29/fall-2017-rfun-workshops/).

#### Introduction to R, the Tidyverse way.

In the first example we've developed guided materials for our [Introduction to R](/intro2r/) (registration:  [Sept. 11](http://duke.libcal.com/event/3442483), [Oct. 17](http://duke.libcal.com/event/3442545)).  Students can clone resources -- from the embedded github link -- into their own R installation.  All the resources are developed in R.  We've even used the `learnr` shiny app, which greatly simplifies the process of generating online/interactive quizzes.  

#### Reproducibility: Data Management, Git, & RStudio
The second resource is hands-on materials supporting our new workshop on [Reproducibility with Git and RStudio](/git/) ([registration](http://duke.libcal.com/event/3442538)).  The workshop will offer a gentle introduction to Git via RStudio. Users will gain hands-on, practical experience creating and manipulating a repository. Attendees will arrive with their own laptop and be guided past the obscure Git configuration process. Upon completion, users will have configured their own laptop with Git, and learned how to leverage Git’s version control in repositories. Following the workshop, researcher will be well positioned to collaborate or simply exercise public (and private) repository control.  We also introduce [OSF.io](https://osf.io/r6wfk/) as a useful data management project site: merging version control with project reproducibility for easy and practical research data management.  




