---
title: Fall 2017 RFUN Workshops
author: John Little
date: '2017-08-29'
slug: fall-2017-rfun-workshops
categories:
  - calendar
  - schedule
  - Workshops
---

## The RFun Series is Back

Introducing the Fall 2017 RFun Series.  We've expanded and transformed the series to add more hands-on training opportunities.  Links to registration are below.   

Each R workshop will take place on a Monday, beginning in mid-September.  Individual workshops will last two hours.  The series will extend over four consecutive weeks followed by a brief respite.  The fifth and final workshop will introduce Shiny, a package for developing interactive web visualizations. The workshop line-up is intended to gently build knowledge and ensures subsequent sessions remain engaging and practicable.

1. Intro to R: Data Transformations, Analysis, and Data Structures ([Sept. 11](http://duke.libcal.com/event/3442483?hs=a), Repeated [Oct. 17](http://duke.libcal.com/event/3442545?hs=a))
1. Reproducibility: Data Management, Git, & RStudio ([Sept. 18](http://duke.libcal.com/event/3442538?hs=a))
1. Visualization in R using ggplot2 ([Sept. 25](http://duke.libcal.com/event/3442555?hs=a))
1. Mapping with R ([Oct. 2](http://duke.libcal.com/event/3442511?hs=a))
1. Developing Interactive Websites with R and Shiny ([Oct. 19](http://duke.libcal.com/event/3442422?hs=a))

## Registration
Dates and details are available through our [DVS Workshops Registration](http://library.duke.edu/data/news) page.  Advanced registration with a Duke NetID is required.  

## Access to Workshop Materials
Importantly, **advanced registration is not** a conduit to receiving **an announcement** regarding recordings.  I note this here to remind people to avoid squatting on limited seating.  Squatting is unnecessary since **all workshops will be recorded**.  Workshop materials, slide presentations, and data will be **shared publicly following** the actual workshops.  See the [DVS past workshops](http://library.duke.edu/data/news/past-workshops) page for access and availability.  

