---
title: RFun@duke.edu email list
author: John Little
date: '2017-08-28'
slug: rfun-duke-edu-email-list
categories:
  - Announcement
  - Twitter
  - Email-List
---

Last spring we introduced the RFun email list as a way of communicating about upcoming events.  The intent of this list is to further announcements for our workshop audience regarding the RFun series.  We hope you will find this list both informative and low-traffic.  Below is a review of ways you can keep in touch with our activities:

- This RFun list:  rfun@duke.edu.  Manage your subscription via https://lists.duke.edu/sympa/info/rfun

- This RFun webpage:  http://rfun.library.duke.edu

- DVS Announce.  A Departmental list reporting news about Data & Visualization Services.  Most of this traffic is about workshops as well.  The scope is slightly broader than the RFun list which focuses exclusively on R.  Manage your subscription via https://lists.duke.edu/sympa/info/dvs-announce

- Twitter: [\@duke_data](http://twitter.com/duke_data) or [\@duke_vis](http://twitter.com/duke_vis)

- DVS Web Site: http://library.duke.edu/data.  RFun is hosted by the datavis group in the Library.  Officially we are the Data & Visualization Services Department (DVS).  We aim to help the Duke University campus learn practical approaches when working with data and visualizations.  Asside from our learning materials (guides and video), you can also find our walk-in support hours and information about in our nifty lab.




